FROM continuumio/miniconda

LABEL name="qtest000-test-ranalysis"
LABEL maintainer="{{ cookiecutter.author_name }}" <"{{ cookiecutter.author_email  }}">  
LABEL version="1.0.0"
LABEL organization="Quantitative Biology Center"
LABEL github="https://github.com/qbicsoftware"