FROM continuumio/miniconda

LABEL name="qtest-ranalysis"
LABEL maintainer="{{ cookiecutter.author_name }}" <"{{ cookiecutter.author_email  }}">  
LABEL version="{{ cookiecutter.container_version }}"
LABEL organization="Quantitative Biology Center"
LABEL github="https://github.com/qbicsoftware"