#!/usr/bin/env python
""" r-lint: Linting tool for R analysis container """

from __future__ import print_function

import click
import logging

import r_lint
import r_lint.lint

@click.group()
@click.version_option(r_lint.__version__)
@click.option(
    '-v', '--verbose',
    is_flag = True,
    help = "Verbose output (print debug statements)"
)

def r_lint_cli(verbose):
    if verbose:
        logging.basicConfig(level=logging.DEBUG, format="\n%(levelname)s: %(message)s")
    else:
        logging.basicConfig(level=logging.INFO, format="\n%(levelname)s: %(message)s")

)

@nf_core_cli.command()
@click.argument(
    'pipeline_dir',
    type = click.Path(exists=True),
    required = True,
    metavar = "<R project directory>"
)

def lint(pipeline_dir):
    """ Check R project against linting guidelines """

    lint_obj = r_lint.lint.RContainerLint(pipeline_dir)


if __name__ == '__main__':
    r_lint_cli()

