FROM r-base:3.2.4

LABEL maintainer="{{ cookiecutter.author_name }}" < "{{ cookiecutter.author_email }}">  
LABEL version="{{ cookiecutter.container_version }}"
LABEL github="https://github.com/qbicsoftware"